version: "3.8"

services:
  backend:
    build: ./back
    container_name: store-backend
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your_secret
      - BCRYPT_SALT_ROUNDS=10
    command: ["sh", "-c", "npx prisma migrate dev && npm run start"]

  frontend:
    build:
      context: ./front
      args:
        VITE_API_URL: http://backend:3000  
    container_name: store-frontend
    ports:
      - "8080:80"  
    depends_on:
      - backend

  db:
    image: "nouchka/sqlite3"
    container_name: store-db
    volumes:
      - ./back/dev.db:/app/dev.db