version: '3.8'
services:
  front:
    build: ./front/.
    container_name: front
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "8080:80"
  back:
    build: ./back/.
    container_name: back
    environment:
      DATABASE_URL: "file:./file.db"
      JWT_SECRET: "your_secret"
      BCRYPT_SALT_ROUNDS: 10
    command: >
      sh -c "
        npx prisma db push
        node server.js
      "
    ports:
      - "3000:3000"
 
  