# Utiliser une image de base officielle de Node.js
FROM node:22-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Installer OpenSSL
RUN apt-get update -y && apt-get install -y openssl

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances de l'application
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

RUN npx prisma generate

# Démarrer l'application
CMD ["node", "./server.js"]