version: '3.8'

services:
  app:
    build: .
    container_name: back
    environment:
      DATABASE_URL: "file:./file.db"
      JWT_SECRET: "your_secret"
      BCRYPT_SALT_ROUNDS: 10
    command: >
      bash -c "
        npx prisma db push
        node server.js
      "
    ports:
      - "3000:3000"