# Build stage
FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

ENV DATABASE_URL="file:./file.db"
ENV JWT_SECRET="your_secret"
ENV BCRYPT_SALT_ROUNDS=10

# Install only production dependencies
RUN npm install  

RUN apk update \
  && apk add --no-cache openssl\
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/cache/apk/*

COPY . .

RUN npx prisma generate 
RUN npx prisma db push

# Production stage
FROM node:22-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

EXPOSE 3000

CMD ["node", "./server.js"]
